### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by park-brian** [hackathonismb/VizSNP-St#9]
Hello, thank you for developing this tool.

When running the `VizSNPSt.py` script locally, I've found that I need to install additional dependencies:
- pandas
- pysam
- requests

Would it be possible to add a requirements.txt that contains these dependencies? This would enable users to install all dependencies using: 

`pip install -r requirements.txt`

I can open a pull request if this is preferable.

**Comment by manojmw** [comment]
Hi Park,

Many thanks for bringing this to our attention and for your interest in our work.

- We have addressed the issue and updated the dependencies required in the README file.

- Additionally, as requested, I have also added a `requirements.txt` file that allows the user to install the required dependencies using the command:

```
pip3 install -r requirements.txt
```

Please feel free to let us know if you have any further questions.

Thanks,
Manoj
